### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by junmin-Chang** [junmin-Chang/CatsOnMyKnee#5]
- [ ] form validation
- [x] upload picture feature
- [ ] 쓰레기같은 코드 갈아치우기
  - [ ] user 불러올 때 cat 불러오지 않고 따로 불러와서 recoil로 관리
